#!/bin/csh
#PBS -S /bin/sh
#PBS -N dompi
#PBS -l nodes=1:ppn=8
#PBS -l walltime=1:00:00
#PBS -q singlepe
#PBS -j oe

cat `echo $PBS_NODEFILE`
module load openmpi
cd $PBS_O_WORKDIR
mpirun -np 1 /usr/local/R-2.15.0/bin/R --no-save < hello_dompi.R
